[package]
distribution = "2201.1.0"
org = "ballerinax"
name = "salesforce"
version = "7.1.0"
export = ["salesforce", "salesforce.bulk", "salesforce.soap"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-sfdc"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../salesforce-native/build/libs/salesforce-native-7.1.0.jar"
groupId = "io.ballerinax"
artifactId = "salesforce"
version = "7.1.0"
